version: '3.8'

services:

  frontend:
    container_name: desafio-frontend
    build:
      context: .
      dockerfile: Docker/frontend/frontend.Dockerfile
    volumes:
      - ./frontend:/home/node/app
    ports:
      - "5179:5179"
    networks:
      - desafio-network

  backend:
    container_name: desafio-backend
    build:
      context: .
      dockerfile: Docker/backend/backend.Dockerfile
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:8000"
    
    networks:
      - desafio-network
    links:
      - "db"

  db:
    container_name: desafio-db
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: desafio
      #MYSQL_USER: desafio
      #MYSQL_PASSWORD: root
    volumes:
      - ./Docker/mysql:/var/lib/mysql
    ports:
      - "3310:3306"
    networks:
      - desafio-network

networks:
  desafio-network:
    driver: bridge
